### ISSUE TITLE
有什么办法可以直接确保自己的url都是英文吗？

### ISSUE THREAD

**Issue by JIeJaitt** [CH3COOOH/simply-static-fixpath#1]
如题

**Comment by CH3COOOH** [comment]
> 如题

目前能想到的只有在设置-固定链接里，把固定链接结构设置为不含中文标题的格式，比如日期或者编号

**Comment by JIeJaitt** [comment]
@CH3COOOH 我发现这个并不能很好的转换代码块，大佬看看这个我转换后的网站：https://sass.jiejaitt.top/2024/12/02/27.html
我在本地docker的样式是：
![image](https://github.com/user-attachments/assets/95ad796a-37d8-4462-8a64-3cefd3447091)

**Comment by CH3COOOH** [comment]
@JIeJaitt 这个工具只对文件名生效，不会修改网页内容哈

**Comment by JIeJaitt** [comment]
不是的大佬，我说是是生成静态文件的那个wp插件

**Comment by CH3COOOH** [comment]
@JIeJaitt 你写文章用的是wp的默认编辑器吗。我用的是markdown编辑器，转换效果还行。这里放个例子：https://blog.henchat.net/generate-a-self-signed-certificate-with-openssl-fully-simplified/

**Comment by JIeJaitt** [comment]
大佬用的是哪个markdown插件

**Comment by CH3COOOH** [comment]
> 大佬用的是哪个markdown插件 爱喝玉米浆 ***@***.***

用的是WP Editor.md

**Comment by JIeJaitt** [comment]
我用了这个插件之后好像写出来的代码块不会自带主题的代码高亮样式

**Comment by CH3COOOH** [comment]
可以的吧。需要指定代码语言的
